project:
  type: book
  output-dir: docs

metadata-files:
  - _metadata.yml

book:
  title: "SFDA | PSY HSE"
  subtitle: "Statistics for Data Analysis"
  author: "Anton Angelgardt"
  date: today
  chapters:
    - index.qmd
    - part: "Введение в статистику"
      chapters: 
        - intro-intro.qmd
        - intro-randvals.qmd
    - part: "Описательная статистика"
      chapters: 
        - desc-centraltend.qmd
        - desc-variation.qmd
        - desc-normdist.qmd
        # - desc-ci.qmd
    # - part: "Статистика вывода"
    #   chapters: 
    #     - infer-stattesting.qmd
    #     - infer-categorical.qmd
    #     - infer-correlation.qmd
    #     - infer-anovaI.qmd
    #     - infer-anovaII.qmd
    #     - infer-posthoc.qmd
    #     - infer-simplelinear.qmd
    #     - infer-multiplelinear.qmd
    #     - infer-ancova.qmd
    #     - infer-logreg.qmd
    #     - infer-cluster.qmd
    #     - infer-efa.qmd
    #     - infer-cfa.qmd
    # - part: "Анализ данных в R"
    #   chapters: 
    #     - r-intro.qmd
    #     - r-preproc.qmd
    #     - r-vis.qmd
    #     - r-lm.qmd
    #     - r-anova.qmd
    #     - r-glm.qmd
    #     - r-cluster.qmd
    #     - r-efa.qmd
    #     - r-cfa.qmd
    # - outro.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme:
     - cosmo
     - custom.scss
  pdf:
    documentclass: scrreprt



