# Простая линейная регрессия

Ненадолго откатимся обратно к корреляции. Она позволяет тестировать гипотезы о связях между количественными переменными. Однако кроме проверки наличия или отсутствия связей между переменными, нас ещё интересует, как бы мы могли управлять одними переменными с помощью других. Для этого необходимо построение некоторой модели.

Когда мы строили диаграммы рассеяния, мы добавляли на них линию тренда, которая отражала линейную составляющую связи между визуализируемыми переменными.


Эта линия и есть интересующая нас модель. Визуально мы такую линию проведём очень легко, а вот как мы нам получить её математическое выражение?

14.1 Формализация модели
Первое, что нужно вспомнить — это общее уравнение прямой. Оно выглядит так:

y
=
k
x
+
b
,
 

где  
k
  — угловой коэффициент (slope), задающий угол наклона прямой к оси  
x
 , а  
b
  — свободный член (intercept), который обозначает ординату точки пересечения прямой с осью  
y
 .

Итого, чтобы получить уравнение прямой, нам надо знать два этих числа. Что у нас есть, для этого есть? У нас есть наши наблюдения — то есть  
x
  и  
y
 .

Мы привыкли к тому, что  
x
  и  
y
  являются неизвестными, но теперь, когда мы ищем уравнение прямой на основе имеющихся измерений, ситуация изменяется.

Запишем уравнение, используя общепринятие обозначения.

y
=
b
0
+
b
1
x
 

Уравнение отражает зависимость между переменными  
x
  и  
y
 , значения которых нам известны, так как у нас есть результаты измерений, а вот неизвестными теперь являются  
b
0
  и  
b
1
 .

В терминах статистической модели:

переменная  
y
  называется зависимая, предсказываемая, целевая переменная или регрессант
переменная  
x
  носит названия независимая переменная, предиктор или регрессор
b
0
  и  
b
1
  называются коэффициентами или параметрами модели.
Важно! Несмотря на использование терминов зависимая и независимая переменные, необходимо чётко понимать, что сам регрессионный анализ, как и корреляционный, ничего нам не говорит о причинности. Мы выражаем  
y
  через  
x
 , но точно так же можем выразить и  
x
  через  
y
  — и модель будет подобрана, так как нет никаких математических ограничений. Поэтому если мы хотим сделать по результатам регрессионного анализа вывод о причинно-следственной связи между явлениями, нам необходимо либо серьёзное теоретическое обоснование нашего вывода — почему мы выбрали в качестве зависимой и независимой переменных именно эти? — либо использование экспериментельного дизайна исследования, где мы обосновываем причинно-следственный характер связи именно через дизайн эксперимента.

14.2 Идентификация модели
Идентификация модели сводится к нахождению коэффициентов  
b
0
  и  
b
1
 . Мы хотим провести такую прямую, которая наилучшим образом будет описывать имеющуюся в данных закономерность, поэтому необходимо найти критерий, по которому мы будем определять «хорошесть» нашей прямой.

Графически мы делаем вот что: проводим прямую через облако точек. Очевидно, что красная прямая описывает закономерность совсем плохо, зелёная — чуть получше, а синяя — то, что нам нужно.


Из картинки также очевидно, что даже синяя прамая не описывает наши данные максимально точно — не все точки попали на прямую. Ясно, что такой прямой мы провести и не сможем — точек же целое облако. Поэтому любая построенная нами модель будет содержать ошибку — вновь по причине вариативности и неопределенности данных. Таким образом, модель, «хорошесть» которой мы пытаемся определить выглядит так:

y
i
=
b
0
+
b
1
x
i
+
e
i
 

А графически ошибки будут тут:


Уравнение же нашей модели вот такое:

^
y
=
b
0
+
b
1
x
 

Игрек в шляпке показывает, что это моделируемое значение нашей целевой переменной, и оно отличается от того, которое есть в данных.

Собственно, задача идентификации модели — минимизировать ошибку модели, подбирая её параметры.

Q
r
e
s
=
n
∑
i
=
1
 
e
2
i
=
n
∑
i
=
1
 
(
y
i
−
(
b
0
+
b
1
x
i
)
)
2
=
n
∑
i
=
1
 
(
y
i
−
^
y
i
)
2
→
min
b
0
,
b
1
 
 

Ошибки модели  
e
i
  также называются остатки (residuals), то есть то, что модель не смогла объяснить. Обозначенное выше условие минимизации ошибки лежит в основе метода наименьших квадратов.

14.2.1 Метод наименьших квадратов
Осторожно! Очень математично!
В сухом остатке из метода наименьших квадратов на надо вынести вот что:

задача индентификации модели линейной регрессии имеет аналитическое решение — то есть мы можем подобрать коэффициенты модели, опираясь только на имеющиеся данные
и оно вот такое
⎧
⎪
⎨
⎪
⎩
b
0
=
¯
y
−
b
1
¯
x
b
1
=
¯¯¯¯¯¯
x
y
−
¯
x
⋅
¯
y
σ
2
x
=
∑
(
x
i
−
¯
x
)
(
y
i
−
¯
y
)
∑
(
x
i
−
¯
x
)
2
 

Это, безусловно, радостно и приятно.

А если вы умеете в матрицы, то всё ещё проще
14.3 Тестирование качества модели
Супер! Мы построили модель! Теперь надо понять, насколько она хороша для наших данных. Но перед этим нам надо сделать шаг назад и прояснить ряд моментов, на которые мы имплицитно опираемся, но пока ещё не проговорили.

Мы помним, что работая с выборкой, мы хотим получить информацию о генеральной совокупности. Строя модель, мы предполагаем, что в генеральной совокупности есть связь, которая описывается следующим уравнением:

y
i
=
β
0
+
β
1
x
i
+
ε
i
 

Таким образом, построив модель, мы получили оценки генеральных параметров:

b
0
=
^
β
0
,
b
1
=
^
β
1
,
e
i
=
^
ε
i
 

Кроме того, при построении модели мы также исходили из нескольких предположений.

Во-первых, мы считали, что связь между предикторами и зависимой переменной линейная.
Во-вторых, мы предположили, что наша модель полностью улавливает тренд закономерности, то остатки (ошибки) модели случайны. Их среднее равно нулю:  
¯
ε
=
0
 ,
а также остатки модели не коррелируют между собой:  
cor
(
ε
i
ε
j
i
≠
j
 
)
=
0
 .
Ну, а раз остатки заключают в себе случайный компонент модели, то они должны быть распределены нормально  
ε
∼
N
(
0
,
σ
2
)
 ,
причём их дисперсия должна быть одинакова при любых значениях предиктора  
σ
2
i
=
σ
2
=
c
o
n
s
t
 .
Так-с, ну, теперь можно приступать с анализу модели.

14.3.1 Коэффициент детерминации
Первое, что хочется понять — насколько наша модель информативна. Иначе говоря, сколько дисперсии наших данных она смогла объяснить. На практике работают не с дисперсией, а с суммой квадратов, что почти то же самое — это мы уже видели в дисперсионном анализе.

Вся изменчивость наших данных (total sum of squares, TSS) определяется так:

TSS
=
n
∑
i
=
1
 
(
¯
y
−
y
i
)
2
 

На одной из картинок нам уже встречалась «красная модель» — это и было среднее по выборке. То есть графически TSS выглядит так:


Одну часть этой изменчивости объясняет модель (explained sum of squares, ESS):

ESS
=
n
∑
i
=
1
 
(
¯
y
−
^
y
i
)
2
 


Другую часть этой изменчивости модель не улавливает, и она остаётся необъяснённой (остаточной) (residual sum of squares, RSS):

RSS
=
n
∑
i
=
1
 
(
y
i
−
^
y
i
)
2
 


Очевидно (особенно по графику), что

TSS
=
ESS
+
RSS
 

Не очевидно! Ты ещё в прошлый раз обещал пояснить!
В качестве метрики информативности модели используется коэффициент детерминации  
R
2
 , который вычисляется по формуле:

R
2
=
ESS
TSS
=
1
−
RSS
TSS
,
 

из чего следует, что  
0
≤
R
2
≤
1
 , а значит коэффициент детерминации может быть интерпретирован как доля дисперсии данных, которую смогла объяснить модель.

Считается, что если модель объясняется 0.8 и более дисперсии данных, то она хороша, хотя этот порог о-о-очень сильно зависит от конкретной задачи и исследовательской области.

Кстати, вопрос на подумать: может ли коэффициент детерминации быть отрицательным?

14.3.2 Статистическая значимость модели
На основе всё тех же сумм квадратов мы можем сделать вывод о том, насколько в целом наша модель статистически значима. Для этого нам надо заняться тестированием некоторой статистической гипотезы. Она формулируется так:

H
0
:
β
0
=
β
1
=
0
H
1
:
β
0
≠
0
∨
β
1
≠
0

Для тестирования данной гипотезы используется следующая статистика:

F
=
MS
e
MS
r
=
ESS
/
d
f
e
RSS
/
d
f
r
H
0
∼
F
(
d
f
e
,
d
f
r
)
,
 

где  
d
f
e
=
p
−
1
 ,  
d
f
r
=
n
−
p
−
1
 ,  
p
  — число предикторов в модели,  
n
  — число наблюдений.

Как и всегда, для  
F
 -статистики рассчитывается p-value, на основе значения которого мы делаем статистический вывод о статистическом равенстве коэффициента детерминации нулю, а следовательно, о статистической значимости модели в целом.

14.3.3 Статистическая значимость отдельных предикторов
Если модель значима в целом, значит среди её коэффициентов есть те, которые статистически отличны от нуля. Иначе говоря, есть такие предикторы, которые значимо связаны с нашей целевой переменной. В случае простой линейной регрессии предиктора всего два — intercept и slope. Intercept не всегда интерпретабелен, поэтому основное внимание уделяют угловому коэффициенту.

Статистическая значимость коэффициента тестируется так:

H
0
:
β
1
=
0
H
1
:
β
1
≠
0
t
=
b
1
−
β
1
SE
b
1
=
b
1
SE
b
1
H
0
∼
t
(
df
=
n
−
p
−
1
)
,

где  
SE
b
1
=
s
r
∑
n
i
=
1
(
x
i
−
¯
x
)
2
 ,  
s
2
r
=
∑
n
i
=
1
(
y
i
−
^
y
)
2
n
−
2
 

Хвала небесам, оно все считается само.

14.3.4 Результаты регрессионного анализа
Результаты представляются в табличке:

Предиктор	Значение	Стандартная ошибка	 
t
 	 
p
 
Интерсепт	 
b
0
 	 
SE
b
0
 	 
t
b
0
 	p-value
Угловой коэффициент	 
b
1
 	 
SE
b
1
 	 
t
b
1
 	p-value
Посмотрим на данные из индустрии. У нас есть данные некоторой компании, в которых есть переменная fot (ФОТ — фонд оплаты труда) и переменная grade_score (интегральный балл по грейду). С первой всё ясно — количество денег, которое заложено на оплату труда сотрудника. Со второй переменной всё чуть сложнее — это оценка сотрудника, рассчитываемая по некоторой схеме, неизвестной нам, ибо NDA1.

Ну, да бох с ним, как там этот грейд рассчитывается. Нам ведь для построения регрессии важно что — чтобы была некоторая целевая количественная переменная, и некоторый предиктор, тоже количественный. У нас есть и то, и другое.

Посмотрим на связь двух переменных:



Картинка местами прикольная и даже забавная, но в целом мы наблюдаем некоторую положительную взаимосвязь между переменными, линия тренда с положительным наклоном — норм, можно пытаться это всё дело моделировать.

Регрессионный анализ нам покажет что-то такое:

## 
## Call:
## lm(formula = fot ~ grade_score, data = ds)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -171435  -28467   -3305   15470  418192 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -7.483e+04  3.358e+03  -22.28   <2e-16 ***
## grade_score  1.118e+00  2.433e-02   45.98   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 47450 on 1993 degrees of freedom
## Multiple R-squared:  0.5147, Adjusted R-squared:  0.5145 
## F-statistic:  2114 on 1 and 1993 DF,  p-value: < 2.2e-16
Таблица невероятно похожа на результаты дисперсионного анализа, не так ли? Падазритильна…

Некоторые отличия, конечно, есть — пройдемся по колонкам:

Estimate — оценка коэффициента при нашем предикторе, то есть  
b
1
 
Std. Error — стандартная ошибка коэффициента (нужна для вычисления следующей колонки)
t value — t-статистика, используемая для тестирования статистической значимости предиктора
это уже знакомый нам t-тест, который был в корреляционном анализе
Pr(>|t|) — это так обозвали p-value, которые рассчитывается для t-статистики
Кроме таблицы, нам нужны еще две последние строчки, в которых указан  
R
2
  и  
F
 -статистика со своим p-value.

Что можно заключить по результатам анализа?

Во-первых, что модель в целом статистически значима (F(1, 1993) = 2114, p < .001) и объясняет 51% дисперсии данных.
Во-вторых, что предиктор модели (grade_score, интегральный балл по грейду) также статистически значим.
Ну, красота.

14.3.5 Интерпретация коэффициента при предикторе
— А ежели наш предиктор значим, то это же получается, что коэффициент при нем статистически отличен от нуля?
— Да, именно так.
— А можем ли мы его каким-либо образом содержательно проинтерпретировать?
— Да.
— А как?
— Ровно так, как [возможно] говорили на математике.

Вообще угловой коэффициент показывает, на сколько изменится целевая переменная при увеличении предиктора на единицу. Поэтому мы можем сказать, что при увеличении ингерального балла по грейду на единицу фонд оплаты труда сотрудника возрастает на 1118₽.

Дорого-богато.

14.4 Диагностика модели
Окей, наша модель значима в целом, а значит значимы и её предикторы, она объясняет приемлемую долю дисперсии данных. Неужели этого недостаточно?

Недостаточно. При построении модели мы исходили из ряда предпосылок. Напомним их:

линейность связи
нормальность распределения остатков и нулевое математическое ожидание
равенствво дисперсии остатков при различных значениях предикторов (гомоскедастичность)
независимость остатков от предикторов модели
Линейность связи можно проверить визуализацией корреляции между переменными.

Другие предпосылки мы можем проверить с помощью диагностических графиков.



Данные графики позволяют провести диагностику модели.

Нормальность распределения остатков отображена на втором графике (Normal Q-Q). Если все наблюдения находятся на или близко к пунктирной линии, то распределение остатков не отличается от нормального. В данном случае мы наблюдаем, что в области верхних квантилей (правая второна графика) остатки модели начинают ползти вверх — значит наша модель не до конца ухватывает имеющуюся закономерность.

Первый (Residual vs Fitted) и третий (Scale-Location) графики позволяют проверить независимость остатков от предикторов модели и требование гомоскедастичности. На графике не должно определяться никаких явных паттернов. В данном случае мы видим, что на первом графике (Residual vs Fitted) разброс остатков по мере движения по оси  
x
  слева направо постепенно увеличивается — не выполнено требование гомоскедастичности. На третьем графике (Scale-Location) выявляется паттерн линейной связи (обратите внимание на расположение красной линии), что говорит о том, что требование независимости остатков модели от предикторов не выполнено. Итого, вновь модель не до конца ухватывает имеющиеся закономерности.

Последний график позволяет определить влиятельные наблюдения. Это такие наблюдения, удаление/добавление которых сильно повлияет на положение регрессионной прямой. В данном случае все наблюдения располагаются в пределах критических значений (серая пунктирная линия в правом верхнем углу).

Что можно заключить по результатам диагностики модели? Модель необходимо дорабатывать. Она ловит часть закономерности, присутствующей в данных, но необходимо вводить дополнительные предикторы, чтобы регрессия ухватывала имеющуюся закономерность более полно.

14.5 Корреляция vs регрессия
Есть некоторый регрессионный хайп о том, что «корреляция — отстой метод, и регрессия — кул». Методы, действительно похожи, однако попробуем разобраться, что к чему.

Сходства
Оба метода тестируют гипотезы о связях
Если мы не имеет дела с экспериментальным дизайном — там предшествование во времени и отсутствие третьих переменных контролируется именно на уровне дизайна, что позволяет нам делать причинно-следственные связи
Оба метода — корреляция и простая линейная регрессия — работают с количественными переменными
Различия
Корреляция нам дает только количественное выражение силы и направления связи. Регрессия строит модель, которую мы можем использовать для предсказаний на новых данных.
Корреляция позволяет тестировать гипотезу о связях только между двумя переменными. Регрессия позволяет включать в модель несколько предикторов.
Итого, если у вы работаете только с двумя переменными, в целом, решительно всё равно, делаете вы корреляционный анализ или регрессионный. Конечно, если у вас стоит исследовательская задача, а не предиктиквная — тогда регрессия. Если же вы хотите изучать более сложные закономерности, то добро пожаловать в следующую главу.

Non-disclosure agreement, соглашение о неразглашении.↩︎

