<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Анализ категориальных данных – SFDA | PSY HSE</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./infer-ttest.html" rel="next">
<link href="./infer-stattesting.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8e19f8179356a23097222aafac55d87a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Ничего не найдено",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Очистить",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Отмена",
    "search-submit-button-title": "Отправить",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./infer-stattesting.html">Статистика вывода</a></li><li class="breadcrumb-item"><a href="./infer-categorical.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Анализ категориальных данных</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">SFDA | PSY HSE</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Начало</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Введение в&nbsp;статистику</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Основания статистики</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-randvals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Шкалы и&nbsp;случайные величины</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Описательная статистика</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./desc-centraltend.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Меры центральной тенденции</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./desc-variation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Меры разброса</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./desc-normdist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Нормальное распределение</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./desc-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Доверительные интервалы</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Статистика вывода</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-stattesting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Тестирование статистических гипотез</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-categorical.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Анализ категориальных данных</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Сравнение средних</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Корреляционный анализ</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-anovaI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Однофакторный дисперсионный анализ</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-simplelinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Простая линейная регрессия</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Содержание</h2>
   
  <ul>
  <li><a href="#categorical-crosstab" id="toc-categorical-crosstab" class="nav-link active" data-scroll-target="#categorical-crosstab"><span class="header-section-number">8.1</span> Анализ таблиц сопряженности</a>
  <ul class="collapse">
  <li><a href="#categorical-crosstab-theor" id="toc-categorical-crosstab-theor" class="nav-link" data-scroll-target="#categorical-crosstab-theor"><span class="header-section-number">8.1.1</span> Теоретические частоты</a></li>
  <li><a href="#categorical-crosstab-indpearson" id="toc-categorical-crosstab-indpearson" class="nav-link" data-scroll-target="#categorical-crosstab-indpearson"><span class="header-section-number">8.1.2</span> Критерий независимости Пирсона</a></li>
  <li><a href="#categorical-crosstab-chisqdist" id="toc-categorical-crosstab-chisqdist" class="nav-link" data-scroll-target="#categorical-crosstab-chisqdist"><span class="header-section-number">8.1.3</span> Распределение <span class="math inline">\(\chi^2\)</span></a></li>
  <li><a href="#categorical-crosstab-effectsize" id="toc-categorical-crosstab-effectsize" class="nav-link" data-scroll-target="#categorical-crosstab-effectsize"><span class="header-section-number">8.1.4</span> Размер эффекта для&nbsp;критерия независимости Пирсона</a></li>
  </ul></li>
  <li><a href="#categorical-other" id="toc-categorical-other" class="nav-link" data-scroll-target="#categorical-other"><span class="header-section-number">8.2</span> Критерий согласия Пирсона</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./infer-stattesting.html">Статистика вывода</a></li><li class="breadcrumb-item"><a href="./infer-categorical.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Анализ категориальных данных</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="infer-categorical" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Анализ категориальных данных</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Сегодня мы изучим первый статистический метод, который применяется при&nbsp;анализе категориальных данных. Напомню, что&nbsp;категориальные данные&nbsp;— это те, которые измерены в&nbsp;номинальной (реже&nbsp;— порядковой) шкале. А&nbsp;раз они измерены в&nbsp;номинальной шкале, значит наши данные разбиваются на&nbsp;некоторые категории (группы). А&nbsp;раз есть категории, значит можно посчитать их частоты. А&nbsp;раз можно посчитать частоты, значит можно построить таблицу частот.</p>
<section id="categorical-crosstab" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="categorical-crosstab"><span class="header-section-number">8.1</span> Анализ таблиц сопряженности</h2>
<p>Таблицы частот для&nbsp;одной переменной мы с&nbsp;вами строили, когда обсуждали меры центральной тенденции, а&nbsp;именно <a href="desc-centraltend.html#centraltend-mode">моду</a>. Однако теперь нас интересует не&nbsp;одна переменная, а&nbsp;две&nbsp;— мы будем искать связь между двумя категориальными переменными.</p>
<p>Давайте на&nbsp;примере. Пусть у&nbsp;нас есть данные о&nbsp;том, как студенты некоторого курса сдали экзамен по&nbsp;анализу данных. Экзамен проходил во&nbsp;вторник. При&nbsp;этом известно, что&nbsp;одна часть студентов усиленно готовилась к&nbsp;экзамену, а&nbsp;другая часть&nbsp;— отмечала понедельник в&nbsp;барах на&nbsp;Китай-городе.</p>
<p>В&nbsp;цифрах:</p>
<ul>
<li>всего студентов на&nbsp;курсе 120 человек</li>
<li>успешно сдали экзамен 94 студента</li>
<li>готовились к&nbsp;экзамену 86 студентов</li>
<li>готовились и&nbsp;не&nbsp;сдали экзамен 3 студента</li>
</ul>
<p>По этим данным мы можем построить <strong>таблицу сопряженности (contingency table, cross tabulation, crosstab)</strong> (<a href="#tbl-crosstabshort" class="quarto-xref">Таблица&nbsp;<span>8.1</span></a>).</p>
<div id="tbl-crosstabshort" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crosstabshort-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;8.1: Таблица сопряженности по&nbsp;имеющимся данным
</figcaption>
<div aria-describedby="tbl-crosstabshort-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Сдали экзамен</th>
<th style="text-align: center;">Не сдали экзамен</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Готовились</td>
<td style="text-align: center;"><span class="math inline">\(83\)</span></td>
<td style="text-align: center;"><span class="math inline">\(3\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Отмечали понедельник</td>
<td style="text-align: center;"><span class="math inline">\(11\)</span></td>
<td style="text-align: center;"><span class="math inline">\(23\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Эта таблица отображаем совместное распределение респондентов по&nbsp;двум категориальным переменным. Так как каждая переменная является бинарной, то&nbsp;есть принимает только два возможных значения, то&nbsp;всего ячеек в&nbsp;таблице четыре. Возможно, не&nbsp;вполне понятно, почему в&nbsp;каждой из&nbsp;ячеек такие значения&nbsp;— давайте дополним таблицу ещё одной колонкой и&nbsp;ещё одной строкой (<a href="#tbl-crosstablong" class="quarto-xref">Таблица&nbsp;<span>8.2</span></a>).</p>
<div id="tbl-crosstablong" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crosstablong-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;8.2: Таблица сопряженности по&nbsp;имеющимся данным с&nbsp;указанием маргинальных частот
</figcaption>
<div aria-describedby="tbl-crosstablong-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Сдали экзамен</th>
<th style="text-align: center;">Не сдали экзамен</th>
<th style="text-align: center;">Всего по&nbsp;строкам</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Готовились</td>
<td style="text-align: center;"><span class="math inline">\(83\)</span></td>
<td style="text-align: center;"><span class="math inline">\(3\)</span></td>
<td style="text-align: center;"><span class="math inline">\(86\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Отмечали понедельник</td>
<td style="text-align: center;"><span class="math inline">\(11\)</span></td>
<td style="text-align: center;"><span class="math inline">\(23\)</span></td>
<td style="text-align: center;"><span class="math inline">\(34\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Всего по&nbsp;столбкам</td>
<td style="text-align: center;"><span class="math inline">\(94\)</span></td>
<td style="text-align: center;"><span class="math inline">\(26\)</span></td>
<td style="text-align: center;"><span class="math inline">\(120\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Здесь к&nbsp;исходной таблице добавлены <strong>маргинальные частоты</strong> (те, что «стоят на&nbsp;краю таблицы»), отображающие суммы частот по&nbsp;строкам и&nbsp;столбцам. Можно также дать общий вид такой таблицы, так&nbsp;как строиться она всегда будет по&nbsp;одному и&nbsp;тому&nbsp;же алгоритму (<a href="#tbl-crosstabgen" class="quarto-xref">Таблица&nbsp;<span>8.3</span></a>), при&nbsp;этом с&nbsp;использованием введённых в&nbsp;таблица обозначений необходимо отметить, что&nbsp;маргинальные частоты (<span class="math inline">\(n_{1\bullet}\)</span>, <span class="math inline">\(n_{2\bullet}\)</span>, <span class="math inline">\(n_{\bullet1}\)</span>, <span class="math inline">\(n_{\bullet2}\)</span>) и&nbsp;общее количество наблюдений (<span class="math inline">\(n_{\bullet \bullet}\)</span>) определяются следующим образом:</p>
<p><span class="math display">\[
\begin{aligned}
&amp; n_{1\bullet} = n_{11}+n_{12} \\
&amp; n_{2\bullet} = n_{21} + n_{22} \\
&amp; n_{\bullet1} = n_{11} + n_{21} \\
&amp; n_{\bullet2} = n_{12} + n_{22} \\
&amp; n_{\bullet\bullet} = n_{11} + n_{12} + n_{21} + n_{22}
\end{aligned}
\]</span></p>
<div id="tbl-crosstabgen" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crosstabgen-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;8.3: Таблица сопряженности для&nbsp;эмпирических частот в&nbsp;общем виде
</figcaption>
<div aria-describedby="tbl-crosstabgen-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><span class="math inline">\(X_2^{(1)}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(X_2^{(2)}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(X_1^{(\bullet)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(X_1^{(1)}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{11}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{12}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{1\bullet}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(X_1^{(2)}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{21}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{22}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{2\bullet}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(X_2^{(\bullet)}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{\bullet1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{\bullet2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{\bullet \bullet}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Эта таблица отражает <strong>эмпирические частоты</strong>&nbsp;— то&nbsp;есть те, которые были посчитанны на&nbsp;собранных нами данных. Здесь <span class="math inline">\(X_1\)</span> и <span class="math inline">\(X_2\)</span>&nbsp;— наши переменные, индексы <span class="math inline">\(^{(1)}\)</span> и&nbsp;<span class="math inline">\(^{(2)}\)</span> показывают категорию, к&nbsp;которой относится то или иное наблюдение. На&nbsp;пересечении столбца и&nbsp;строки&nbsp;— частота совместного появления признаков <span class="math inline">\(X_1^{(i)}\)</span> и&nbsp;<span class="math inline">\(X_2^{(j)}\)</span>. Суммы частот по&nbsp;строкам и&nbsp;столбцам&nbsp;— маргинальные частоты [строк и&nbsp;столбцов соответственно].</p>
<p>Итак, эмпирические частоты у&nbsp;нас в&nbsp;наличии. Теперь вспомним алгоритм тестирования статистических гипотез:</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Заметка</span>Напоминание: алгоритм тестирования статистических гипотез
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Формулировка гипотезы</li>
<li>Выбор статистического критерия</li>
<li>Выбор уровня значимости <span class="math inline">\(\alpha\)</span></li>
<li>Расчёт выборочной статистики</li>
<li>Построение закона распределения статистики критерия при&nbsp;условии, что&nbsp;нулевая гипотеза верна</li>
<li>Расчёт p-значения (p-value)</li>
<li>Сопоставление <span class="math inline">\(\alpha\)</span> и&nbsp;p-value и&nbsp;статистический вывод</li>
</ol>
</div>
</div>
<section id="categorical-crosstab-theor" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="categorical-crosstab-theor"><span class="header-section-number">8.1.1</span> Теоретические частоты</h3>
<p>Нам нужно сформулировать нулевую гипотезу. Как мы помним, нулевая гипотеза всегда об&nbsp;отсутствии каких-либо различий&nbsp;или взаимосвязей. В&nbsp;нашем случае уместно будет сказать, что&nbsp;<strong>между переменными <span class="math inline">\(X_1\)</span> и&nbsp;<span class="math inline">\(X_2\)</span> нет связи.</strong> Однако это словесное выражение гипотезы&nbsp;— нам&nbsp;же нужно также её как-то математически оформить. Это не&nbsp;только простая задача, как может показаться.</p>
<p>Как буду вести себя совместные частоты (<span class="math inline">\(n_{11}\)</span>, <span class="math inline">\(n_{12}\)</span>, <span class="math inline">\(n_{21}\)</span>, <span class="math inline">\(n_{22}\)</span>), если между переменными нет взаимосвязи? Интуитивно хочется сказать, что&nbsp;все они будут равны:</p>
<p><span class="math display">\[
n_{11} = n_{12} = n_{21} = n_{22}
\]</span></p>
<p>Что&nbsp;ж, это вполне неплохо для&nbsp;нулевой гипотезы, разве&nbsp;что только вместо эмпирических частот нужно будет найти соответствующий параметр генеральной совокупности. Однако <em>такой расклад будет свитедельствовать об&nbsp;отсутствии взаимосвязи медлу переменными только в&nbsp;ситуации, когда маргинальные частоты равны.</em> Это может быть уместо при&nbsp;анализе экспериментальных данных со&nbsp;сбалансированным дизайном&nbsp;— но&nbsp;это частный случай. Нам&nbsp;бы всё&nbsp;же хотелось сформулировать гипотезу для&nbsp;общего случая.</p>
<p>Хорошо, раз мы не&nbsp;можем принять гипотезу о&nbsp;равенстве «частот», давайте попробуем посмотреть, как вели&nbsp;бы себя совместные частоты <span class="math inline">\(n_{11}\)</span>, <span class="math inline">\(n_{12}\)</span>, <span class="math inline">\(n_{21}\)</span>, <span class="math inline">\(n_{22}\)</span>, если между переменными <span class="math inline">\(X_1\)</span> и <span class="math inline">\(X_2\)</span> нет взаимосвязи и&nbsp;известны маргинальные частоты <span class="math inline">\(n_{1\bullet}\)</span>, <span class="math inline">\(n_{2\bullet}\)</span>, <span class="math inline">\(n_{\bullet1}\)</span>, <span class="math inline">\(n_{\bullet2}\)</span>.</p>
<p>Здесь нам потребуется одна мысль (<a href="#thm-probprod" class="quarto-xref">Теорема&nbsp;<span>8.1</span></a>) из&nbsp;теории вероятностей:</p>
<div id="thm-probprod" class="theorem">
<p><span class="theorem-title"><strong>Теорема 8.1</strong></span> Вероятность совместного появления двух независимых событий равна произведению их вероятностей.</p>
<p><span class="math display">\[
\mathbb{P} (A \cap B) = \mathbb{P} (A) \cdot \mathbb{P} (B)
\]</span></p>
</div>
<p>Эмпирическим аналогом вероятности является <em>частота</em>, поэтому справедливо будет следущее <a href="#prp-freqprod" class="quarto-xref">Утверждение&nbsp;<span>8.1</span></a>.</p>
<div id="prp-freqprod" class="theorem proposition">
<p><span class="theorem-title"><strong>Утверждение 8.1</strong></span> Относительная частота совместного появления двух независимых событий равна произведению их относительных частот.</p>
<p><span class="math display">\[
p_{A \cap B} = p_A \cdot p_B
\]</span></p>
</div>
<p>Строго доказывать теорему и&nbsp;утверждение мы не&nbsp;будем, ограничимся принятием на&nbsp;веру справедливости теоремы и&nbsp;интуитивным соответствием утверждения с&nbsp;ней.</p>
<p>Как нам это поможет? Мы можем вычислить относительные частоты принадлежности наблюдений к&nbsp;каждой из&nbsp;групп по&nbsp;обеим переменным, то&nbsp;есть для&nbsp;нашей таблицы <a href="#tbl-crosstabgen" class="quarto-xref"><span>8.3</span></a>:</p>
<p><span class="math display">\[
\begin{aligned}
&amp; p_{1\bullet} = \dfrac{n_{1\bullet}}{n_{\bullet \bullet}} \\
&amp; p_{2\bullet} = \dfrac{n_{2\bullet}}{n_{\bullet \bullet}} \\
&amp; p_{\bullet1} = \dfrac{n_{\bullet1}}{n_{\bullet \bullet}} \\
&amp; p_{\bullet2} = \dfrac{n_{\bullet2}}{n_{\bullet \bullet}} \\
\end{aligned}
\]</span></p>
<p>Теперь так как нас интересует ситуация независимости двух переменных&nbsp;— а значит, и&nbsp;независимого попадания к&nbsp;каждую из&nbsp;групп по&nbsp;каждой переменной&nbsp;— отноcительная частота попадания наблюдения в&nbsp;группы <span class="math inline">\(p_{11}\)</span>, <span class="math inline">\(p_{12}\)</span>, <span class="math inline">\(p_{21}\)</span> и <span class="math inline">\(p_{22}\)</span> будет вычисляться как произведение вышеобозначенных относительных частот:</p>
<p><span class="math display">\[
\begin{aligned}
&amp; p_{11} = p_{1\bullet} \cdot p_{\bullet1} = \dfrac{n_{1\bullet} \cdot n_{\bullet1}}{n^2_{\bullet \bullet}} \\
&amp; p_{12} = p_{1\bullet} \cdot p_{\bullet2} = \dfrac{n_{1\bullet} \cdot n_{\bullet2}}{n^2_{\bullet \bullet}} \\
&amp; p_{21} = p_{2\bullet} \cdot p_{\bullet1} = \dfrac{n_{2\bullet} \cdot n_{\bullet1}}{n^2_{\bullet \bullet}} \\
&amp; p_{22} = p_{2\bullet} \cdot p_{\bullet2} = \dfrac{n_{2\bullet} \cdot n_{\bullet2}}{n^2_{\bullet \bullet}} \\
\end{aligned}
\]</span></p>
<p>Это почти то, что нам нужно! Вот только в&nbsp;таблице сопряженности у&nbsp;нас фигурируют не&nbsp;относительные частоты, а&nbsp;абсолютные&nbsp;— то есть штуки. Но&nbsp;это легко поправить&nbsp;— нам всего лишь нужно умножить относительную частоту на&nbsp;общее число наблюдений. Таким образом, мы получаем общую формулу для&nbsp;<strong>теоретических частот</strong>:</p>
<p><span class="math display">\[
n^{(\mathrm t)}_{ij} = \frac{n_{i \bullet} \cdot n_{\bullet j}}{n_{\bullet \bullet}}
\]</span></p>
<p>Таблица теоретических частот принимает следующий вид (<a href="#tbl-crosstab-theor" class="quarto-xref">Таблица&nbsp;<span>8.4</span></a>).</p>
<div id="tbl-crosstab-theor" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crosstab-theor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;8.4: Таблица теоретических частот в&nbsp;общем виде
</figcaption>
<div aria-describedby="tbl-crosstab-theor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><span class="math inline">\(X_2^{(1)}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(X_2^{(2)}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(X_1^{(\bullet)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(X_1^{(1)}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n^{(\mathrm t)}_{11} = \dfrac{n_{1 \bullet} \cdot n_{\bullet 1}}{n_{\bullet \bullet}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n^{(\mathrm t)}_{12} = \dfrac{n_{1 \bullet} \cdot n_{\bullet 2}}{n_{\bullet \bullet}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{1\bullet}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(X_1^{(2)}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n^{(\mathrm t)}_{21} = \dfrac{n_{2 \bullet} \cdot n_{\bullet 1}}{n_{\bullet \bullet}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n^{(\mathrm t)}_{22} = \dfrac{n_{2 \bullet} \cdot n_{\bullet 2}}{n_{\bullet \bullet}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{2\bullet}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(X_2^{(\bullet)}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{\bullet1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{\bullet2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{\bullet \bullet}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Обратим внимание на&nbsp;то, какого результата мы добились:</p>
<ul>
<li>мы получили возможность рассчитать теоретические частоты</li>
<li>исходя из&nbsp;того, что&nbsp;между переменными нет взаимосвязи</li>
<li>на&nbsp;основе известных (любых) маргинальных вероятностей.</li>
</ul>
<p>Рассчитаем для&nbsp;примера таблицу теоретических частот, соответствующую данным из&nbsp;таблицы <a href="#tbl-crosstablong-theor" class="quarto-xref"><span>8.5</span></a>:</p>
<div id="tbl-crosstablong-theor" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crosstablong-theor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;8.5: Таблица теоретических частот, соответствующая эмпирическим частотам таблицы <a href="#tbl-crosstablong" class="quarto-xref"><span>8.2</span></a>
</figcaption>
<div aria-describedby="tbl-crosstablong-theor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Сдали экзамен</th>
<th style="text-align: center;">Не сдали экзамен</th>
<th style="text-align: center;">Всего по&nbsp;строкам</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Готовились</td>
<td style="text-align: center;"><span class="math inline">\(\dfrac{86 \cdot 94}{120} = 67.37\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dfrac{86 \cdot 26}{120} = 18.63\)</span></td>
<td style="text-align: center;"><span class="math inline">\(86\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Отмечали понедельник</td>
<td style="text-align: center;"><span class="math inline">\(\dfrac{34 \cdot 94}{120} = 26.63\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dfrac{34 \cdot 26}{120} = 7.37\)</span></td>
<td style="text-align: center;"><span class="math inline">\(34\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Всего по&nbsp;столбцам</td>
<td style="text-align: center;"><span class="math inline">\(94\)</span></td>
<td style="text-align: center;"><span class="math inline">\(26\)</span></td>
<td style="text-align: center;"><span class="math inline">\(120\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Эта таблица нам будет необходима для&nbsp;проверки статистической гипотезы.</p>
<p>Однако мы в творческом порыве как&nbsp;будто&nbsp;бы отвлеклись от&nbsp;главного&nbsp;— мы собирались формулировать нулеву гипотезу. На&nbsp;самом деле, нет, не&nbsp;отвлеклись. Теперь мы гововы её-таки сформулировать.</p>
<p>Поскольку статистическая гипотеза должна содержать <em>параметры генеральной совокупности</em>, значит мы будем формулировать гипотезу про&nbsp;<em>совместную вероятность</em>&nbsp;— популяционный аналог совместной частоты. Эта вероятность при&nbsp;справедливости нулевой гипотезы должна вести себя <strong>соответственно случаю независимости событий</strong>. Итого, получаем, что</p>
<p><span class="math display">\[
\begin{aligned}
&amp; H_0: \pi_{ij} = \pi_{i \bullet} \cdot \pi_{\bullet j} \\
&amp; H_1: \exists (i, j): \pi_{ij} \neq \pi_{i \bullet} \cdot \pi_{\bullet j}
\end{aligned}
\]</span></p>
<p>Что&nbsp;ж, о, ура! Гипотеза наконец сформулирована. Время переходить к&nbsp;выбору статистического критерия.</p>
</section>
<section id="categorical-crosstab-indpearson" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="categorical-crosstab-indpearson"><span class="header-section-number">8.1.2</span> Критерий независимости Пирсона</h3>
<p>Для&nbsp;тестирование заявленной гипотезы подходит <strong>критерий независимости Пирсона (Pearson’s Chi-squared test)</strong>. Как у&nbsp;любого статистического критерия, у&nbsp;него есть <em>статистика критерия</em>, которая вычисляется следующим образом:</p>
<p><span class="math display">\[
\chi^2 = \sum_{i=1}^k \sum_{j=1}^l \frac{(n_{ij} - n_{ij}^{(\text{t})}) ^2 }{n_{ij}^{(t)}} \overset{H_0}{\thicksim} \chi^2 (\text{df}), \,\, \text{df} = (r-1)(c-1)
\]</span> где <span class="math inline">\(\chi^2\)</span>&nbsp;— значение статистики критерия, <span class="math inline">\(n_{ij}\)</span>&nbsp;— эмпирическая совместная частота, <span class="math inline">\(n_{ij}^{(\text{t})}\)</span>&nbsp;— теоретическая совместная частота, <span class="math inline">\(\chi^2(\text{df})\)</span>&nbsp;— распределение <span class="math inline">\(\chi^2\)</span> с&nbsp;параметром <span class="math inline">\(\text{df}\)</span> (степени свободы), <span class="math inline">\(r\)</span>&nbsp;— число строк в&nbsp;таблице сопряженности, <span class="math inline">\(c\)</span>&nbsp;— число столбцов в&nbsp;таблице сопряженности.</p>
<p>По&nbsp;сути формула нам позволяет сравнить, насколько эмпирические частоты отклоняются от&nbsp;теоретических&nbsp;— рассчитанных для&nbsp;случая, когда между переменными нет взаимосвязи. Чем сильнее эти отклонения, тем больше будет наблюдаемое значение статистики критерия.</p>
<p>Это общая формула для&nbsp;таблиц сопряженности любого размера. В&nbsp;рассматриваемом нами случае <span class="math inline">\(k=l=2\)</span>, так как таблица сопряженности имеет размер 2×2. Следовательно, число степеней свобооды в&nbsp;нашем случае будет равно <span class="math inline">\(\text{df} = (2 - 1)(2-1) = 1\)</span>.</p>
<p>В&nbsp;частности, для&nbsp;нашего случая (<a href="#tbl-crosstablong-theor" class="quarto-xref">Таблица&nbsp;<span>8.5</span></a> и&nbsp;<a href="#tbl-crosstablong" class="quarto-xref">Таблица&nbsp;<span>8.2</span></a>):</p>
<p><span class="math display">\[
\begin{aligned}
\chi^2 &amp;= \frac{(83-67.37)^2}{67.37} +
  \frac{(3-18.63)^2)}{18.63} + \\
  &amp; + \frac{(11-26.63)^2}{26.63} +
  \frac{(23-7.37)^2}{7.37} \approx 59.06
\end{aligned}
\]</span> Ура! Мы рассчитали наблюдаемое значение статистики критерия. Далее по&nbsp;алгоритму необходимо выбрать уровень значимости&nbsp;— не&nbsp;будем сильно изощряться и&nbsp;выберем <span class="math inline">\(0.05\)</span>.</p>
<p>Теперь&nbsp;же рассмотрим, распределение статистики критерия при&nbsp;условии, что&nbsp;нулевая гипотеза верна.</p>
</section>
<section id="categorical-crosstab-chisqdist" class="level3" data-number="8.1.3">
<h3 data-number="8.1.3" class="anchored" data-anchor-id="categorical-crosstab-chisqdist"><span class="header-section-number">8.1.3</span> Распределение <span class="math inline">\(\chi^2\)</span></h3>
<p>Почему вообще критерий называется «хи-квадрат»? Потому&nbsp;что распределение статистики критерия независимости Пирсона подчиняется распределению <span class="math inline">\(\chi^2\)</span> при&nbsp;справедливости нулевой гипотезы. Выглядит это распределение так (<a href="#fig-chisqdist" class="quarto-xref">Рисунок&nbsp;<span>8.1</span></a>).</p>
<div id="fig-chisqdist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chisqdist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="infer-categorical_files/figure-html/unnamed-chunk-2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Рисунок&nbsp;8.1: Распределение \chi^2 при&nbsp;различном числе степеней свободы."><img src="infer-categorical_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chisqdist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;8.1: Распределение <span class="math inline">\(\chi^2\)</span> при&nbsp;различном числе степеней свободы.
</figcaption>
</figure>
</div>
<p>Поскольку мы работаем с&nbsp;таблицей сопряженности 2&nbsp;×&nbsp;2 и&nbsp;количество степеней свободы у&nbsp;нас равно 1, то&nbsp;нас будет прицельно интересовать вот это распределение (<a href="#fig-chisqdist-df1" class="quarto-xref">Рисунок&nbsp;<span>8.2</span></a>).</p>
<div id="fig-chisqdist-df1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chisqdist-df1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="infer-categorical_files/figure-html/unnamed-chunk-3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Рисунок&nbsp;8.2: Распределение \chi^2(1)."><img src="infer-categorical_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chisqdist-df1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;8.2: Распределение <span class="math inline">\(\chi^2(1)\)</span>.
</figcaption>
</figure>
</div>
<p>Как мы помним из&nbsp;темы про&nbsp;случайные величины, чем&nbsp;выше график плотности вероятности, тем&nbsp;чаще встречаются значения переменной. В&nbsp;данном случае мы видим, что&nbsp;при&nbsp;справедливости нулевой гипотезы малые значения <span class="math inline">\(\chi^2\)</span> встречаются очень часто&nbsp;— то&nbsp;есть являются типичными. Большие&nbsp;же значения встречаются редко. Это согласуется с&nbsp;тем, что собственно показывает значение статистики <span class="math inline">\(\chi^2\)</span>:</p>
<ul>
<li>малые значения <span class="math inline">\(\chi^2\)</span> соответствуют малым отклонениям эмпирических частот от&nbsp;теоретических, то&nbsp;есть типичны для&nbsp;случая, когда между переменными нет связи;</li>
<li>большие значения <span class="math inline">\(\chi^2\)</span> соответствуют больши́м отклонениям эмпирических частот от&nbsp;теоретических, поэтому нетипичны для&nbsp;случая, когда между переменным нет связи.</li>
</ul>
<p>Отобразим выбранный уровень значимости (красная область в&nbsp;хвосте графика <a href="#fig-chisqdist-df1-alpha" class="quarto-xref"><span>8.3</span></a>)</p>
<div id="fig-chisqdist-df1-alpha" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chisqdist-df1-alpha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="infer-categorical_files/figure-html/unnamed-chunk-4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Рисунок&nbsp;8.3: Критическая область для&nbsp;уровня значимости 0.05 на&nbsp;распределении \chi^2(1)"><img src="infer-categorical_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chisqdist-df1-alpha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;8.3: Критическая область для&nbsp;уровня значимости 0.05 на&nbsp;распределении <span class="math inline">\(\chi^2(1)\)</span>
</figcaption>
</figure>
</div>
<p>Мы немного ограничили ось <span class="math inline">\(y\)</span> в&nbsp;пределах от&nbsp;0 до&nbsp;0.3, чтобы лучше видеть, что&nbsp;происходит&nbsp;— это связано с&nbsp;сильно асимметричной формой распределения. Красная область под&nbsp;графиком&nbsp;— это то, что&nbsp;мы назвали <strong>критическая область</strong>, или&nbsp;область <strong>отклонения нулевой гипотезы</strong>, она&nbsp;же <strong>область статистического вывода</strong>.</p>
<p>Итак, принципиально возможны две ситуации:</p>
<ul>
<li>рассчитанное значение <span class="math inline">\(\chi^2\)</span> попало в&nbsp;критическую область (<a href="#fig-chisqdist-df1-pval-1" class="quarto-xref">Рисунок&nbsp;<span>8.4 (a)</span></a>)
<ul>
<li>в&nbsp;этом случае <span class="math inline">\(\mathsf{p} &lt; \alpha\)</span>
<ul>
<li>следовательно, мы получили значение статистики критерия, <strong>нехарактерное</strong> для&nbsp;случая, когда верна нулевая гипотеза
<ul>
<li>значит, у&nbsp;нас <strong>есть основания отклонить</strong> нулевую гипотезу и&nbsp;принять альтернативную;</li>
</ul></li>
</ul></li>
</ul></li>
<li>рассчитанное значение <span class="math inline">\(\chi^2\)</span> не&nbsp;попало в&nbsp;критическую область (<a href="#fig-chisqdist-df1-pval-2" class="quarto-xref">Рисунок&nbsp;<span>8.4 (b)</span></a>)
<ul>
<li>в&nbsp;этом случае <span class="math inline">\(\mathsf{p} &gt; \alpha\)</span>
<ul>
<li>следовательно, мы получили значение статистики критерия, <strong>характерное</strong> для&nbsp;случая, когда верна нулевая гипотеза
<ul>
<li>значит, у&nbsp;нас <strong>нет оснований отклонить</strong> нулевую гипотезу.</li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<div id="fig-chisqdist-df1-pval" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chisqdist-df1-pval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-chisqdist-df1-pval" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-chisqdist-df1-pval-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-chisqdist-df1-pval-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="infer-categorical_files/figure-html/fig-chisqdist-df1-pval-1.png" class="lightbox" data-gallery="fig-chisqdist-df1-pval" title="Рисунок&nbsp;8.4&nbsp;(a): p < α"><img src="infer-categorical_files/figure-html/fig-chisqdist-df1-pval-1.png" class="img-fluid figure-img" data-ref-parent="fig-chisqdist-df1-pval" width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-chisqdist-df1-pval-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) p &lt; α
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-chisqdist-df1-pval" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-chisqdist-df1-pval-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-chisqdist-df1-pval-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="infer-categorical_files/figure-html/fig-chisqdist-df1-pval-2.png" class="lightbox" data-gallery="fig-chisqdist-df1-pval" title="Рисунок&nbsp;8.4&nbsp;(b): p > α"><img src="infer-categorical_files/figure-html/fig-chisqdist-df1-pval-2.png" class="img-fluid figure-img" data-ref-parent="fig-chisqdist-df1-pval" width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-chisqdist-df1-pval-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) p &gt; α
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chisqdist-df1-pval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;8.4: p-value для&nbsp;<span class="math inline">\(\chi^2\)</span> в&nbsp;случае попадания и&nbsp;не&nbsp;попадания значения в&nbsp;критическую область.
</figcaption>
</figure>
</div>
<p>Глядя на&nbsp;значение статистики критерия, рассчитанное для&nbsp;нашего случая&nbsp;— напомню, мы насчитали выше <span class="math inline">\(\chi^2 \approx 59.06\)</span>&nbsp;— и&nbsp;сопоставив его с&nbsp;картиной <a href="#fig-chisqdist-df1-alpha" class="quarto-xref"><span>8.3</span></a>, можно прикинуть, что&nbsp;<span class="math inline">\(\mathsf{p} &lt; .001\)</span>, следовательно, отклоняя нулевую гипотезу, мы можем сказать, что&nbsp;в&nbsp;<em>данном исследовании</em> обнаружено, что&nbsp;подготовка к&nbsp;экзамену связана с&nbsp;успешностью его сдачи. Вот&nbsp;это новость никогда&nbsp;бы не&nbsp;подумали…</p>
</section>
<section id="categorical-crosstab-effectsize" class="level3" data-number="8.1.4">
<h3 data-number="8.1.4" class="anchored" data-anchor-id="categorical-crosstab-effectsize"><span class="header-section-number">8.1.4</span> Размер эффекта для&nbsp;критерия независимости Пирсона</h3>
<p>То, что&nbsp;мы обнаружили различия или&nbsp;взаимосвязь&nbsp;— это хорошо. Но&nbsp;какова <em>сила</em> этой связи? Иначе говоря, какова величина <strong>размера эффекта</strong>?</p>
<div id="def-effectsize" class="theorem definition">
<p><span class="theorem-title"><strong>Определение 8.1</strong></span> <strong>Размер эффекта</strong>&nbsp;— численное выражение силы взаимосвязи между переменными (или различий между группами).</p>
</div>
<p>Ну, пусть так. У&nbsp;нас ведь уже посчитана статистика <span class="math inline">\(\chi^2\)</span>, и&nbsp;как мы говорили выше, она оценивает величину отклонений эмпирических частот от&nbsp;теоретических, что&nbsp;в&nbsp;общем-то и&nbsp;показывает величину различий. Да? Да&nbsp;же?</p>
<p>Отчасти да, но&nbsp;нет. Значение статистики критерия&nbsp;— любого, и&nbsp;критерий согласия Пирсона здесь не&nbsp;исключение&nbsp;— зависит от&nbsp;числа наблюдений. Так, мы может получить большое значение <span class="math inline">\(\chi^2\)</span> даже при&nbsp;малых различиях в&nbsp;частотах, если объём выборки достаточно велик. Следовательно, сама статистика критерия не&nbsp;подходит для&nbsp;оценки размера эффекта.</p>
<p>Метрик размера эффекта для&nbsp;критерия независимости Пирсона существует несколько, из&nbsp;всех мы ограничимся упоминанием <span class="math inline">\(\varphi\)</span>-коэффициента и&nbsp;<span class="math inline">\(V\)</span> Крамера.</p>
<section id="categorical-crosstab-effectsize-phi" class="level4" data-number="8.1.4.1">
<h4 data-number="8.1.4.1" class="anchored" data-anchor-id="categorical-crosstab-effectsize-phi"><span class="header-section-number">8.1.4.1</span> <span class="math inline">\(\varphi\)</span>-коэффициент</h4>
<p>Эта метрика размера эффекта считается на&nbsp;основе значения статистики <span class="math inline">\(\chi^2\)</span>, «убирая» из&nbsp;неё влияние количества наблюдений:</p>
<p><span class="math display">\[
\varphi = \sqrt{\frac{\chi^2}{N}}
\]</span></p>
<p>Данная метрика применяется для&nbsp;таблица сопряженности 2×2, которые наиболее часто встречаются в&nbsp;практике. Значение <span class="math inline">\(\varphi\)</span>-коэффициента изменяются в&nbsp;пределах от&nbsp;0 до&nbsp;1, а&nbsp;для&nbsp;интерпретации предлагаются следующие пороговые значения:</p>
<ul>
<li><span class="math inline">\(0.10\)</span>&nbsp;— малый эффект</li>
<li><span class="math inline">\(0.30\)</span>&nbsp;— средний эффект</li>
<li><span class="math inline">\(0.50\)</span>&nbsp;— большой эффект</li>
</ul>
</section>
<section id="categorical-crosstab-effectsize-v" class="level4" data-number="8.1.4.2">
<h4 data-number="8.1.4.2" class="anchored" data-anchor-id="categorical-crosstab-effectsize-v"><span class="header-section-number">8.1.4.2</span> <span class="math inline">\(V\)</span> Крамера</h4>
<p>Для&nbsp;таблиц сопряженности любого размера подходит метрика <span class="math inline">\(V\)</span> Крамера, считающаяся несколько похоже на&nbsp;<span class="math inline">\(\varphi\)</span>-коэффициент:</p>
<p><span class="math display">\[
V = \sqrt{\frac{\chi^2}{N \cdot \min(r-1, c-1)}},
\]</span></p>
<p>где <span class="math inline">\(r\)</span> и&nbsp;<span class="math inline">\(c\)</span>&nbsp;— количество строк и&nbsp;столбцов в&nbsp;таблице сопряженности соответственно.</p>
<p>Интерпретация значения <span class="math inline">\(V\)</span> Крамера зависит от&nbsp;числа степеней свободы, которое для&nbsp;этой статистиски считается как <span class="math inline">\(df = \min(r-1, c-1)\)</span>:</p>
<ul>
<li><span class="math inline">\(\text{df} = 1\)</span> — совпадает с&nbsp;<span class="math inline">\(\varphi\)</span>-коэффициентом:
<ul>
<li><span class="math inline">\(0.10\)</span>&nbsp;— малый эффект</li>
<li><span class="math inline">\(0.30\)</span>&nbsp;— средний эффект</li>
<li><span class="math inline">\(0.50\)</span>&nbsp;— большой эффект</li>
</ul></li>
<li><span class="math inline">\(\text{df} = 2\)</span>:
<ul>
<li><span class="math inline">\(0.07\)</span>&nbsp;— малый эффект</li>
<li><span class="math inline">\(0.21\)</span>&nbsp;— средний эффект</li>
<li><span class="math inline">\(0.35\)</span>&nbsp;— большой эффект</li>
</ul></li>
<li><span class="math inline">\(\text{df} = 3\)</span>:
<ul>
<li><span class="math inline">\(0.06\)</span>&nbsp;— малый эффект</li>
<li><span class="math inline">\(0.17\)</span>&nbsp;— средний эффект</li>
<li><span class="math inline">\(0.29\)</span>&nbsp;— большой эффект</li>
</ul></li>
</ul>
<!---
## Другие критерии для анализа частотных данных {#categorical-other}

Упомянем ещё два критерия, которые могут встретиться --- хотя, вероятно, значительн реже, чем критерий независимосни Пирсона --- в исследовательской практике. Не будем погружаться в детали вычисления, ограничимся рассмотрением их практического применения.
--->
</section>
</section>
</section>
<section id="categorical-other" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="categorical-other"><span class="header-section-number">8.2</span> Критерий согласия Пирсона</h2>
<p>Кроме критерия независимости Пирсона, существует ещё критерий согласия Пирсона. По&nbsp;сути, это некоторая вариации того, что мы изучили выше&nbsp;— и&nbsp;он даже проще, так как мы сравниваем эмпирические частоты с&nbsp;некоторыми заранее известными теоретическими. Собственно, поэтому он называется критерием согласия&nbsp;— согласовано ли&nbsp;наше эмпирическое распределение с&nbsp;некоторым заранее известным теоретическим.</p>
<p>Откуда мы знаем теоретические частоты? Ну, в&nbsp;общем случае&nbsp;— ниоткуда. Ведь это частоты генеральной совокупности, а о ней, как известно, ничего достоверно неизвестно. По&nbsp;этой причине любые критерии согласия в&nbsp;целом используются в&nbsp;исследовательской практике весьма редко. Обычно они являются частью какого-либо другого статистического метода.</p>
<p>И&nbsp;все&nbsp;же исследовательскую задач для&nbsp;критерия согласия Пирсона придумать можно. Скажем, вы аппробируете психометрический опросник, и&nbsp;вам надо показать, что&nbsp;ваша выборка аппробации репрезентативна относительно генеральной совокупности в&nbsp;отношении распределения респондентов по&nbsp;полу. Генеральная совокупность&nbsp;— Российская Федерация. Где взять теоретические частоты&nbsp;— ведь мы не&nbsp;можем исходить из&nbsp;предположения, что&nbsp;доли мужчин и&nbsp;женщин в&nbsp;России одинаковы? Хвала небесам, у&nbsp;нас есть Росстат&nbsp;— он&nbsp;же Федеральная служба государственной статистики&nbsp;— который нам рассказал, что&nbsp;мужчин в&nbsp;РФ 46%, а&nbsp;женщин по&nbsp;несложным подсчетам&nbsp;— 54%.</p>
<p>Пусть мы собрали выборку в&nbsp;495 человек, из&nbsp;которых 262&nbsp;— мужчины, а 233&nbsp;— женщины. Таковы наши эмпирические частоты. Теоретические частоты будут рассчитываться по&nbsp;формуле <span class="math inline">\(n_i^{(\text{t})} = p_i \cdot N\)</span>, где <span class="math inline">\(p_i\)</span>&nbsp;— теоретическая доля, <span class="math inline">\(N\)</span>&nbsp;— количество наблюдений в&nbsp;выборке. Итого, для&nbsp;мужчин <span class="math inline">\(0.46 \cdot 495 = 227.7\)</span>, а&nbsp;для&nbsp;женщин <span class="math inline">\(0.54 \cdot 495 = 267.3\)</span>.</p>
<ul>
<li>Формула для&nbsp;расчета <strong>статистики критерия</strong> вот:</li>
</ul>
<p><span class="math display">\[
\chi^2 = \sum_{i} \frac{(n_i - n_i^{(\text{t})})^2}{n_i^{(\text{t})}} \overset{H_0}{\thicksim} \chi^2(c-1),
\]</span> где <span class="math inline">\(c\)</span>&nbsp;— количество колонок в&nbsp;таблице частот.</p>
<ul>
<li><strong>Нулевая гипотеза</strong> (ограничимся нестрогой словесной формулировкой): эмпирические частоты не&nbsp;отличаются от&nbsp;теоретических.</li>
<li><strong>Статистический вывод</strong> выполняется по&nbsp;стандартному алгоритму.</li>
</ul>
<p>Для&nbsp;нашего случая имеем:</p>
<p><span class="math display">\[
\chi^2 = \frac{(262 - 227.7)^2}{227.7} + \frac{(233 - 267.3)^2}{267.3} \approx 9.56
\overset{\chi^2(1)}{\Rightarrow} \mathsf{p} \approx .002
\]</span></p>
<p>Снова видим <span class="math inline">\(\mathsf{p} &lt; \alpha\)</span> (приняв <span class="math inline">\(\alpha = 0.05\)</span>), значит мы получили значение статистики, не&nbsp;характерное для&nbsp;ситуации справедливости нулевой гипотезы, и&nbsp;у&nbsp;нас есть основания отклонить нулевую гипотезу и&nbsp;принять альтернативную о&nbsp;том, что&nbsp;эмпирические частоты отличаются от&nbsp;теоретических.</p>
<p>Получается, что наша выборка не особо репрезентативна. Грустно…</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Скопировано!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Скопировано!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./infer-stattesting.html" class="pagination-link" aria-label="Тестирование статистических гипотез">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Тестирование статистических гипотез</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./infer-ttest.html" class="pagination-link" aria-label="Сравнение средних">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Сравнение средних</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>